# Numpy Answer sheet

In [22]:
import numpy as np

### Exercise 1:
Run the cells above a couple of times. Do you ever see 10 appear? (spoiler: you won't). Adjust the code above such that 10 can also appear.

In [ ]:
np.random.randint(1, 11, 3)

### Exercise 2: Create a matrix of 3 by 3 and retrieve the number at location (2, 1)

In [5]:
#store the data in a variable called 'my_data'
my_data = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

#retrieve the number at location (2, 1). 
my_data[2][1]

8

### Exercise 3:  Create a array with values ranging from 10 up to and including 49
(**hint**: np.arange)

In [6]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### Exercise 4: obtain the 7th element of the array
Replace the ```___``` in the following cell to complete the excercise.

In [7]:
X = np.arange(1,11)

#

# replace the ___ with the appropriate code
seventh_element = X[6]
print("The seventh element =", seventh_element)

The seventh element = 7


### Exercise 5: use slicing to get the first two elements of the last two rows

In [8]:
Y= np.array([[ 1,  2,  3,  4],
             [ 5,  6,  7,  8],
             [ 9, 10, 11, 12],
             [13, 14, 15, 16]])

#

# replace the ___ with the appropriate code
Y[2:4, 0:2]

array([[ 9, 10],
       [13, 14]])

### Exercise 6: use slicing to replace the first two elements of the last two rows with 0's

In [10]:
Y= np.array([[ 1,  2,  3,  4],
             [ 5,  6,  7,  8],
             [ 9, 10, 11, 12],
             [13, 14, 15, 16]])

#

# replace the ___ with the appropriate code
Y[2:4, 0:2] = np.zeros((2,2))
Y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 0,  0, 11, 12],
       [ 0,  0, 15, 16]])

### Exercise 7:  Create an array of zeros of size 10 but the fifth value is equal to 1
(**hint**: np.zeros and indexing)

In [12]:
X = np.zeros(10)
X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### Exercise 8: use the drop-down menu to find a function that calculates the minimum of an array

In [13]:
X = np.arange(1, 11)
np.min(X)

1

### Exercise 9: find the median of values in X

In [14]:
X = np.random.randint(0, 10)

# replace ___ with the appropriate code
np.median(X)

4.0

### Exercise 10:  Create a 10x10 array with random values and find the minimum and maximum values
(**hint**: see above how to create random arrays)

In [16]:
X = np.random.randint(0, 10, (10, 10))

# replace ___ with the appropriate code
print(np.min(X))
print(np.max(X))

0
9


### Exercise 11: create an array of 30 random values and find the mean value
(**hint**: mean)

In [13]:
X = np.arange(1, 11)
np.min(X)

1

### Challenge 1: create an array of size (5,5) with values 1,2,3,4 just below the diagonal and 0's elsewhere
(**hint**: np.diag)

In [ ]:
n = np.zeros((5,5))
np.diag([0,1,2,3,4])

### Challenge 2: sort array Y to be sorted from left to right AND top to bottom. 
In other words, the lowest number is in the top left corner and the highest number in the bottom right corner.

In [4]:
Y = np.random.randint(1,5, (3,3))

#

Y2 = Y.flatten()
Y2.sort()
np.reshape(Y2, (3,3))

array([[1, 2, 2],
       [2, 2, 3],
       [4, 4, 4]])

### Exercise 12: filter to show only numbers that end with 5, 6 or 7.

In [21]:
X = np.random.randint(1, 20, 50)

X[((X >=5) & (X <= 7)) | ((X >=15) & (X <= 17))]

array([17,  6, 15, 15, 17,  6,  6, 15, 17, 16,  5,  6])